name: Docker Image CI

on:
  schedule:
  - cron: 23 15 13 */2 *
  push:
    branches:
    - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: |
        Image="docker.pkg.github.com/danopia/reggie/reggie"
        GitHash="$(git describe --always --long --dirty)"
        GitImage="$Image:$GitHash"
        docker build -t "$GitImage" .
        docker tag "$GitImage" "$Image:latest"
        { echo "$GitImage"; echo "$Image:latest"; } > images.txt

    - name: Push the image to GPR
      run: |
        docker login docker.pkg.github.com -u danopia -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
        cat images.txt | xargs -n1 -- docker push
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
